baseURL = "/"
languageCode = "en-us"
title = "Corey Weber"
theme = "hugo-initio"
publishDir = "docs"

[params]
    name = "Corey Weber"
    description = "Web Developer"
    email = "coreyweber11@gmail.com"
    phone = "1(902)388-1552"
    address = "www.coreyweber.ca"
    year = 2018
    background = ""
    favicon = "images/favicon.ico"
    DateForm = "February 2, 2018"

    showSubheader = true
    showExperiences = true
    showRecentWorks = false
    showResume= true

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "about"
    url = "/about/"
    weight = 5
[[menu.main]]
    name = "contact"
    url = "/contact/email/"
    weight = 6

[params.disqus]
    site = "coreyweber.ca"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"


[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/coreyweber/"
    icon = "fa-linkedin-square"
    footer = true
    sharethis = false
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/coreyweb"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:coreyweber11@gmail.com"
    icon = "fa-envelope"
    footer = true
    sharethis = false
    network = "email"
